- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep myapp-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep myapp-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      shell: kubectl create deploy myapp --image=lerndevops/samplejavaapp:{{ build }}
    - name: increase replicas 
      shell: kubectl scale deploy myapp --replicas=2
    - name: deploy service
      shell: kubectl expose deployment myapp --name myapp-svc --type NodePort --port 80 --target-port 8080 --node-port 30001
