apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    app: addressbookapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addressbookapp
  template:
    metadata:
      labels:
        app: addressbookapp
    spec:
      containers:
      - name: addressbookapp
        image: lerndevops/addressbook
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: addressbookapp-svc
spec:
  type: NodePort
  selector:
    app: addressbookapp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
